name: runtests

on: [push, pull_request]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental == 'nightly' }}
    strategy:
      matrix:
        julia-version: ['1.3', '1.4', '1.5', '1.6-nightly']
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@master
        timeout-minutes: 1
